name: Docs
on:
    push:
        branches:
            - main
permissions:
    contents: write
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
jobs:
    docs:
        runs-on: ubuntu-latest
        env:
            # connection string for service container
            POSTGRES_CONNECTION_STRING: 'postgresql://postgres:password@localhost:5432/ci?sslmode=disable'
            BASE_URL: 'localhost:5173'
            PUBLIC_PREVIEW_HOST: 'https://example.com/'
            PUBLIC_LIBRARY_ID: 000000
            BUNNY_API_KEY: ''
            DISCORD_CLIENT_ID: ''
            DISCORD_CLIENT_SECRET: ''
            GITHUB_CLIENT_ID: ''
            GITHUB_CLIENT_SECRET: ''
        strategy:
            matrix:
                node-version: [20.x]
        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_DB: ci
                    POSTGRES_PASSWORD: password
                    POSTGRES_PORT: 5432
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install Dependencies
              run: npm ci --include=dev
            - name: Run migrations
              run: npm run migrate
            - uses: k1low/setup-tbls@v1
            - name: Run tbls for generate database document
              run: tbls doc $POSTGRES_CONNECTION_STRING src/lib/server/db
            - name: Build docs
              run: npx typedoc --tsconfig ./tsconfig.json
            - name: Push to `gh-pages`
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  clean: true
                  folder: docs
                  git-config-name: Channel-Surfer CI
                  git-config-email: <>
