name: Docs
on:
    push:
        branches:
            - main
            - add-db-docs
permissions:
    contents: write
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
jobs:
    docs:
        runs-on: ubuntu-latest
        env:
            # connection string for service container
            POSTGRES_CONNECTION_STRING: 'postgresql://postgres:password@postgres:5432/ci-db'
        strategy:
            matrix:
                node-version: [20.x]
        services:
            # Label used to access the service container
            postgres:
                # Docker Hub image
                image: postgres
                # Provide the password for postgres
                env:
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: ci-db
                # Set health checks to wait until postgres has started
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install Dependencies
              run: npm ci --include=dev
            - name: Run migrations
              run: npm run migrate
            - name: Checkout .tbls.yml
              uses: actions/checkout@v3
            - uses: k1low/setup-tbls@v1
            - name: Run tbls for generate database document
              run: tbls doc $POSTGRES_CONNECTION_STRING
            - name: Build docs
              run: npx typedoc
            - name: Push to `gh-pages`
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  clean: true
                  folder: docs
                  git-config-name: Channel-Surfer CI
                  git-config-email: <>
