permissions:
    contents: read
on:
    push:
        branches: [main]
    pull_request:
# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
name: lint
jobs:
    prettier:
        runs-on: ubuntu-latest
        name: prettier
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: npm ci
            - name: prettier
              run: './.github/workflows/lint.sh'
    eslint:
        runs-on: ubuntu-latest
        name: eslint
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - uses: actions/checkout@v4
              with:
                  submodules: true
            - run: npm ci
            - name: prettier
              run: node .github/workflows/eslint.js
